SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) TOTAL_SALES
FROM AUTHOR
INNER JOIN BOOK USING (AUTHOR_ID)
INNER JOIN BOOK_SALES USING (BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;