SELECT HISTORY_ID, ROUND(DAILY_FEE*(100-IFNULL(DISCOUNT_RATE, 0))/100 * D) FEE
FROM
(
    SELECT A.CAR_ID, A.CAR_TYPE, DAILY_FEE, HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 D, 
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 7 THEN '7일 이상'
        ELSE '7일 미만' 
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    INNER JOIN CAR_RENTAL_COMPANY_CAR A USING (CAR_ID)
) TA
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON TA.CAR_TYPE = PLAN.CAR_TYPE AND TA.DURATION_TYPE = PLAN.DURATION_TYPE
WHERE TA.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;